"""Add boarding_deadline and boarded fields to Reservation model

Revision ID: 0861d3e286c7
Revises: f62b27f45e46
Create Date: 2026-03-02 10:07:41.899289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0861d3e286c7'
down_revision = 'f62b27f45e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boarding_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('boarded', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('boarded')
        batch_op.drop_column('boarding_deadline')

    # ### end Alembic commands ###
