"""Add is_deleted field to rides for soft delete support

Revision ID: 8b0f87cc6d7e
Revises: 963e0824f1da
Create Date: 2026-02-25 13:52:10.012775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0f87cc6d7e'
down_revision = '963e0824f1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE rides SET is_deleted = false WHERE is_deleted IS NULL")
    
    # Make column non-nullable
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.alter_column('is_deleted', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
