"""add role and status to employees

Revision ID: 942050fbc9f0
Revises: a62012baf615
Create Date: 2026-02-18 10:57:24.434690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942050fbc9f0'
down_revision = 'a62012baf615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='employee', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
