"""Add cancelled_at field to Ride model

Revision ID: 963e0824f1da
Revises: 61af607c0676
Create Date: 2026-02-25 13:19:17.862999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963e0824f1da'
down_revision = '61af607c0676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')

    # ### end Alembic commands ###
