"""add_coordinate_fields_to_rides

Revision ID: f62b27f45e46
Revises: 8b0f87cc6d7e
Create Date: 2026-02-25 15:29:15.456436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62b27f45e46'
down_revision = '8b0f87cc6d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('origin_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('destination_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('destination_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_column('destination_lng')
        batch_op.drop_column('destination_lat')
        batch_op.drop_column('origin_lng')
        batch_op.drop_column('origin_lat')

    # ### end Alembic commands ###
